# https://hydra.cc/docs/configure_hydra/intro/

# output directory, generated dynamically on each run
run:
  dir: ${hydra:runtime.cwd}/outputs/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${hydra:runtime.cwd}/outputs/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
