name: pre-commit
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.4.10"
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ hashFiles('**/requirements-dev.lock') }}
      - name: Install dependencies
        run: |
          uv pip install --no-cache --system -r requirements-dev.lock
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always
